  export const radiologists = [
    {
      id: 1,
      name: "Dr. Sagar Tyagi",
      designation: "Senior Radiologist",
      experience: "10 years experience overall",
      location: "Dwarka Sector 10, Delhi",
      consultationFee: "₹1500 Consultation fee at clinic",
      hospital: "Max Super Speciality Hospital + 1 more",
      avatarUrl: "https://via.placeholder.com/100",
      isVerified: true,
    },
    {
      id: 2,
      name: "Dr. Neha Sharma",
      designation: "Radiologist",
      experience: "8 years experience overall",
      location: "Connaught Place, Delhi",
      consultationFee: "₹1200 Consultation fee at clinic",
      hospital: "Apollo Hospital",
      avatarUrl: "https://via.placeholder.com/100",
      isVerified: true,
    },
    {
      id: 3,
      name: "Dr. Rahul Verma",
      designation: "Radiologist",
      experience: "5 years experience overall",
      location: "Gurgaon Sector 56",
      consultationFee: "₹1000 Consultation fee at clinic",
      hospital: "Fortis Hospital",
      avatarUrl: "https://via.placeholder.com/100",
      isVerified: false,
    },
  ];
